### ISSUE TITLE
Now it is broken

### ISSUE THREAD

**Issue by XP-Fan** [lieuwex/whapp-irc#32]
Since yesterday the whole thing is broken: I can still connect to IRC, and it welcomes me and tells me to enjoy the ride, however, I do not get any QR-Code any longer and status does not show up with its messages at all.

**Comment by lieuwex** [comment]
I have the same problem now all of a sudden, weird, maybe it has to do with 2e1b259b5504bb224642b78ad2637e59e003ef59. I will investigate.

**Comment by XP-Fan** [comment]
Maybe you can give us the previous version that worked for now?

**Comment by lieuwex** [comment]
@XP-Fan it should be fixed now, I can't give older versions (I think), since docker cloud only stores the newest version (I guess). The problem was in the fact that chromium was updated and somewhere something wasn't right. Now I force the build to use an older chromium version which seem to work again.
