### ISSUE TITLE
docker image tagging

### ISSUE THREAD

**Issue by skibz** [lieuwex/whapp-irc#43]
some of us are using your docker image for "production" usage - i'm not going to go into details of what that entails 😉

what i will say, however, is that when new images are pushed without an explicit tag (defaulting to `latest`) everyone downstream of this project runs the risk of pulling an image with bugs or regressions that may have slipped by since previous additions and/or pushes.

that being said, having a tag to pin to is easy and solves this problem. if you are open to this idea, then i recommend tagging images with an atomically incrementing integer, eg: `lieuwex/whapp-irc:v1`, `lieuwex/whapp-irc:v2`, `lieuwex/whapp-irc:v3`, and so on...

**Comment by skibz** [comment]
i'll just pin to your commits 👍

**Comment by lieuwex** [comment]
By pinning to commits do you mean pinning to digests? Or, if you really mean commits, how does one do that? Didn't know that was possible.

I thought about versioning whapp-irc, but everything can break at anytime upstream and stuff, and I don't really know how to version stuff so see it as a CI project. If I _had_ to give it a version number it would be 0.x.x too, so that isn't too special either.
